### ISSUE TITLE
Error logging

### ISSUE THREAD

**Issue by philipce** [nifty-swift/Nifty#16]
Thinking back to our discussion about precondition vs throwing... maybe a there's a better option than both. What if nifty provides a global logging object (similar to python logging) that allows for logging levels debug, info, warning, error, critical. These print the message to the console, to a file, etc depending on what the user has set. They could also have a handler, e.g. the user can pass a closure to execute on occurrence of a particular event. By default, the critical handler is print the message, log to file, then fatalError(). Then, instead of precondition, our errors just use the logger, e.g. `log.critical("Matrix is not invertible")`. In our tests then we can override the default handler to set a flag so we can effectively test for precondition... Thoughts?

**Comment by philipce** [comment]
I totally forgot matlab has `error` and `warning` functions, so this could stay consistent with the matlab api

**Comment by philipce** [comment]
@felix91gr 

Thoughts on this? I've got `warning` and `error` in place in Nifty already. I think I need to go through and backfill some of the work I've already put up that uses `precondition`s and such instead. Then, moving forward, we should *only* use `warning` and `error` (otherwise it's completely untestable).

Before we go to the effort, do you have any thoughts on this?

**Comment by felix91gr** [comment]
Are these `error` and `warning` custom types for Nifty? Swift’s Errors are still not ripe for all use cases (afaik), so using something custom makes a lot of sense.

That said though, there are some open source libraries that allow for standardized error handling in Swift, like antitypical’s [`Result`](https://github.com/antitypical/Result). Maybe we could use one of those, so that we build on their advantages and our users can use something they probably already know to handle Nifty errors.

The backfilling of existing `precondition`s and such, I think is the correct move. I’m 100% in on that.

#### Sidenote

There is a [proposal](https://github.com/jshier/swift-evolution/blob/master/proposals/0187-add-result-to-the-standard-library.md) being [debated](https://lists.swift.org/pipermail/swift-evolution/Week-of-Mon-20171030/040829.html) in the mailing list about putting `Result` in `StdLib`. It doesn’t look like it’s going to be added for this cycle, but well... at least it shows where things may be going regarding error handling, I guess? 🤔

**Comment by philipce** [comment]
Migrated issue to pivotal tracker
