### ISSUE TITLE
Reproducible random programs

### ISSUE THREAD

**Issue by adamduracz** [nifty-swift/Nifty#2]
As far as I can see, there is no way to initialize the random number generators that underlie the rand(), randn() and randi() functions with a seed. It is possible to pass a seed as a parameter, but this means that repeated calls to these functions will always yield the same result.
What I would like to be able to so is to initialize the RNG once with a seed, which would make subsequent calls to any of the rand() functions deterministic.

**Comment by philipce** [comment]
If I understand the issue correctly, I think the following accomplishes what you need:
    
    import Nifty

    // seed the global random number generator
    let _ = randi(seed: 1234)

    for _ in 0..<10
    {
        print(randi())
    }

Each number printed to the screen is different, but I get the same set of 10 numbers every time the script is run. Any call to randi with a seed will seed the global generator (if threadSafe is not set) so it only needs to be passed in once. Does that resolve the issue?

In retrospect, it does seem a little weird to have the call to generate the random number also be the method for global seeding... Thoughts on what interface might be more intuitive?

**Comment by adamduracz** [comment]
Thanks! That does resolve the issue. A more explicit way to initialize the random number generator could be through another procedure, e.g. called "srand()" to initialize the RNG used by "rand()".

**Comment by philipce** [comment]
Cool! I like your idea of an explicit seed function. MATLAB has  the rng()
function for seeding the random number generator, so I'll add in something
analogous

On Feb 2, 2017 2:07 PM, "Adam Duracz" <notifications@github.com> wrote:

Thanks! That does resolve the issue. A more explicit way to initialize the
random number generator could be through another procedure, e.g. called
"srand()" to initialize the RNG used by "rand()".

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/nifty-swift/Nifty/issues/2#issuecomment-277084071>, or mute
the thread
