### ISSUE TITLE
I found a nice testing framework for upgrading our unit tests :D

### ISSUE THREAD

**Issue by felix91gr** [nifty-swift/Nifty#25]
I recently listened to episode 54 of the [Swift Coders Podcast](https://itunes.apple.com/us/podcast/swiftcoders/id1082937962?mt=2), with Robert Widmann, a Core Team intern. Robert (aka [CodaFi](https://github.com/CodaFi)) recommended **Property Testing**, which is like an upgraded form of Unit Testing. 
The idea is to automatically create **random instances** for testing, instead of making them by hand. You can also restrict how they are made, of course. He recommended also [`SwiftCheck`](https://github.com/typelift/SwiftCheck), which is basically Property Testing for Swift... and maintained by him :smile: 

What do you think of it? After playing with the refactoring of the Vector, Matrix and Tensor structs, I'll make some tests with this and see how it goes. I think it could be marvelous to find small bugs in the implementation, that would usually go under the radar with the unit tests :)

**Comment by philipce** [comment]
Hey, great minds think alike! I have played around with SwiftCheck a bit in
another project and was thinking it would be very well suited to this
project.

So what I've been doing in the mean time is putting in a testBasic function
for everything I put up that just has the most basic of hard-coded test
cases, just as a rough sanity check. I'll continue adding a testBasic
function just because I like it as part of my dev process, but I don't
think it's really necessary if instead a more thorough test gets added--as
long as the code coverage stays reasonable (like at least 70-80%).

Originally, the plan was once there was an implementation for everything
that should go in a 1.0 release, to go back and beef up the tests to have a
lot more test cases and push us to essentially 100% coverage. The plan was
to generate huge random data sets for each test case (plus any applicable
well-known tricky cases), have python/matlab scripts that correspond to
each test case operate on that data and write their results out (which
really only needs to be done once), and then have the corresponding xctest
case read the data set, operate on it, and compare to the known results.

Anyway yeah, if you want to try SwiftCheck out, I'd be interested to see
how it goes!

**Comment by felix91gr** [comment]
Haha, nice! Indeed, I too think it's exceptionally well suited for a proyect like this :)

> The plan was to generate huge random data sets for each test case (plus any applicable well-known tricky cases), have python/matlab scripts that correspond to each test case operate on that data and write their results out (which really only needs to be done once), and then have the corresponding xctest case read the data set, operate on it, and compare to the known results.

Oh, that's a good idea too. We might as well end up doing that instead. It's a solid fallback to have, for if we don't manage to use SwiftCheck for all of the test cases :)

**Comment by felix91gr** [comment]
I studied SwitfCheck last weekend, and I think I've got a decent grasp on it now. I think we should use it, it's a fantastic library.

And on other topics: I'm reaching now this semester's final exams, so I'll have little time during most of June. I'll be back stronger around July ^^

**Comment by philipce** [comment]
Cool, let's start using it! I've been moving house and had some big work
deadlines this last little bit so I've been slacking :) Let's talk details
of how we want to use it when we're both a little more free

**Comment by felix91gr** [comment]
I was thinking of using it to test for basic properties that should always hold, like these:

### Vectors
Let a, b, c be vectors, and _c1_, _c2_ scalars. They have the following properties:

#### Dot product
* **Commutative:** a * b = b * a
* **Distributive over addition:** a * (b + c) = a * b + a * c
* **Scalars can be moved in and out:** (_c1_ * a) * (_c2_ * b) = _c1 * c2_ * (a * b)

### Matrices
Let A, B, C, D, etc be matrices. I is the identity, and O is the null matrix

* **Associativity of product:** for all A,B,C: (A * B) * C == A * (B * C)
* **Distributivity:** for all A, B, C: A * (B + C) == A * B + A * C
* **Idempotence:** for all A, A * I == I * A == A
* **Uniqueness of identity:** for all A, B s.t. B != O, if A * B = A, then B == I.
* **Absorbent product element:** for all A, A * O == O * A == O
* **Commutativity:** for all A, B: A + B == B + A
* ...

And so on. There are some, like the properties that include a matrix's **determinant**, or the **identity**, that only apply to square matrices. But there are lots of general properties, [specially in the area of matrix product](https://en.wikipedia.org/wiki/Matrix_multiplication#Properties_of_the_matrix_product_.28two_matrices.29). And the square tests can be made using generators that output square matrices :D 

### Tensors

I still have to learn more about tensors (I'm watching [this playlist on the topic](https://www.youtube.com/playlist?list=PLhCVdH1_jOGz6GHH33R6i_H-w1ETWhEHG)). But I'm sure there are plenty of properties that we can test.

### Misc

There are also some properties for custom operations, like `mean`, that we can deduce and test. For example, we know that for a given Tensor **t**, the mean _M(**t**)_ of all its elements satisfies:

* _M_(**t**) + _c1_ = _M_(**t** + _c1_),

where _c1_ is a constant, and the operation **t** + _c1_ adds _c1_ to all of **t**'s components.

---

What about we make **a list of properties** to test, trying to be as **exhaustive** as we can? We can start it here in a Markdown document, or we can share a google doc and use comments and stuff while we polish the list :)

**Comment by philipce** [comment]
That's a really good idea, I like it! I probably won't be able to get to
much of anything till this weekend, but I'll start thinking of properties.
This is definitely a good idea that extends super naturally for matrix
operations (like inversion, SVD, etc.)

**Comment by felix91gr** [comment]
Closed this one, as #30 is covering the topic formally now :3
